"""empty message

Revision ID: 2b7d1548be43
Revises: 5222bd704eae
Create Date: 2020-02-13 11:14:20.004007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2b7d1548be43'
down_revision = '5222bd704eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('gname', sa.String(length=80), nullable=True))
    op.drop_index('group_name', table_name='user_group')
    op.create_unique_constraint(None, 'user_group', ['gname'])
    op.drop_column('user_group', 'group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('group_name', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'user_group', type_='unique')
    op.create_index('group_name', 'user_group', ['group_name'], unique=True)
    op.drop_column('user_group', 'gname')
    # ### end Alembic commands ###
