"""empty message

Revision ID: 5222bd704eae
Revises: 6087c9c8dca1
Create Date: 2020-02-13 10:38:44.913287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5222bd704eae'
down_revision = '6087c9c8dca1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_2', 'user', type_='foreignkey')
    op.drop_column('user', 'group_id')
    op.add_column('user_group', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_group', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_group', type_='foreignkey')
    op.drop_column('user_group', 'user_id')
    op.add_column('user', sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_2', 'user', 'user_group', ['group_id'], ['id'])
    # ### end Alembic commands ###
