"""empty message

Revision ID: 68f2fadb30d3
Revises: 00186c6c5de2
Create Date: 2020-02-09 15:36:44.228996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '68f2fadb30d3'
down_revision = '00186c6c5de2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat_log', sa.Column('from_user_id', sa.Integer(), nullable=True))
    op.add_column('user_chat_log', sa.Column('to_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('user_chat_log_ibfk_2', 'user_chat_log', type_='foreignkey')
    op.drop_constraint('user_chat_log_ibfk_1', 'user_chat_log', type_='foreignkey')
    op.create_foreign_key(None, 'user_chat_log', 'user', ['to_user_id'], ['id'])
    op.create_foreign_key(None, 'user_chat_log', 'user', ['from_user_id'], ['id'])
    op.drop_column('user_chat_log', 'to_user')
    op.drop_column('user_chat_log', 'from_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_chat_log', sa.Column('from_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_chat_log', sa.Column('to_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_chat_log', type_='foreignkey')
    op.drop_constraint(None, 'user_chat_log', type_='foreignkey')
    op.create_foreign_key('user_chat_log_ibfk_1', 'user_chat_log', 'user', ['from_user'], ['id'])
    op.create_foreign_key('user_chat_log_ibfk_2', 'user_chat_log', 'user', ['to_user'], ['id'])
    op.drop_column('user_chat_log', 'to_user_id')
    op.drop_column('user_chat_log', 'from_user_id')
    # ### end Alembic commands ###
