"""empty message

Revision ID: 91d96b73c2dc
Revises: 2b7d1548be43
Create Date: 2020-02-13 11:21:17.716166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91d96b73c2dc'
down_revision = '2b7d1548be43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('group_name', table_name='user_group')
    op.create_unique_constraint(None, 'user_group', ['gname'])
    op.drop_column('user_group', 'group_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_group', sa.Column('group_name', mysql.VARCHAR(length=80), nullable=True))
    op.drop_constraint(None, 'user_group', type_='unique')
    op.create_index('group_name', 'user_group', ['group_name'], unique=True)
    # ### end Alembic commands ###
