"""empty message

Revision ID: ab9961fd6267
Revises: 91d96b73c2dc
Create Date: 2020-02-13 11:22:27.863255

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ab9961fd6267'
down_revision = '91d96b73c2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_ibfk_3', 'user', type_='foreignkey')
    op.drop_column('user', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('user_ibfk_3', 'user', 'user', ['contact_id'], ['id'])
    # ### end Alembic commands ###
